### ISSUE TITLE
Does it support WuHuClient-all-1.0.4 20240314?

### ISSUE THREAD

**Issue by LucklyJie** [ch1ck3n-ovo/QuickShulker#1]
Does this mod consider linkage with other mods, such as WuHuClient-all-1.0.4 20240314 printers, I believe everyone needs it very much, thank you

**Comment by ch1ck3n-ovo** [comment]
I'm sorry, but this is a plugin for servers. I'm afraid that you can't use this on your client.

**Comment by LucklyJie** [comment]
> 抱歉，这是服务器插件。恐怕你不能在你的客户端上使用这个。

Oh sorry, I didn't pay attention to the title, I think it's also a very good plugin, I'll keep an eye on it
